import P_img from "../../components/project_entry_utils/P_img.tsx"
import five from "./assets/five.png"
import four from "./assets/four.png"
import three from "./assets/three.png"
import two from "./assets/two.png"
import one from "./assets/one.png"
import { githubLink } from "../../routes/projects/SingleProjectPage/links.tsx"
import { Project } from "../../routes/projects/SingleProjectPage/project.ts"
import ProjWrapper from "../../components/project_entry_utils/project_wrapper/ProjWrapper.tsx"
import P_p from "../../components/project_entry_utils/P_p.tsx"
import {
  javaTechnology,
  gpuTechnology,
} from "../../routes/projects/SingleProjectPage/technology.tsx"
import P_ul from "../../components/project_entry_utils/P_ul.tsx"
import P_li from "../../components/project_entry_utils/P_li.tsx"

export const FractalProject: Project = {
  name: "fractal",
  title: "Mandlebrot Fractal Explorer",
  subtitle:
    "An app that renders and allows you to explore the Madlebrot (and burning ship) fractal",
  msSinceEpoch: null,
  image: { image: one, alt: "TODO" },
  technologies: [javaTechnology, gpuTechnology],
  links: [
    {
      url: "https://github.com/Robert-M-Lucas/Mandlebrot-Fractal-GPU",
      type: githubLink,
    },
  ],
  page: FractalEntryPage,
}

function FractalEntryPage() {
  return (
    <ProjWrapper>
      <P_img
        image={one}
        alt={"TODO"}
        caption={
          "Image generated by my program. Originally at 10000x10000 but compressed heavily"
        }
      />
      <P_p>
        This program renders and allows you to explore (pan, zoom in, etc.) the
        Mandlebrot and burning ship fractal as well as render screenshots at a
        resolution higher than your monitor. In theory you would be able to zoom
        in infinitely however the double precision limit is hit after around 20
        zoom ins.
      </P_p>
      <P_p>
        Despite its flaws, this is one of my favourite projects as it was my
        first project in Java and the fractals look beautiful. It is also a nice
        combination of maths and computer science which I both like.
      </P_p>
      <P_p>
        This is one of my older projects, however, and I would like to redo it
        with some improvements:
        <P_ul>
          <P_li>Getting around the double precision limit</P_li>
          <P_li>
            If you zoom in 2x, one pixel should be saved and three new pixels
            generated instead of a complete regeneration
          </P_li>
          <P_li>
            The render feature could save to disk as it runs stopping it from
            being RAM-limited
          </P_li>
        </P_ul>
      </P_p>
      <P_img image={two} alt={"TODO"} />
      <P_img image={three} alt={"TODO"} />
      <P_img image={four} alt={"TODO"} />
      <P_img
        image={five}
        alt={"TODO"}
        caption={"An early test of a more optimised screenshot system"}
      />
    </ProjWrapper>
  )
}
