import ProjImage from "../../components/project_entry_utils/ProjImage.tsx";
import five from "./assets/five.png";
import four from "./assets/four.png";
import three from "./assets/three.png";
import two from "./assets/two.png";
import one from "./assets/one.png";
import {GITHUB_LINK} from "../../routes/projects/SingleProjectPage/links.tsx";
import {Project} from "../../routes/projects/SingleProjectPage/project.ts";
import ProjWrapper from "../../components/project_entry_utils/ProjWrapper.tsx";
import ProjParagraph from "../../components/project_entry_utils/ProjParagraph.tsx";
import {JAVA, GPU} from "../../routes/projects/SingleProjectPage/technology.tsx";
    
export const FractalProject: Project = {
    currently_working_on: false,
    name: "fractal",
    title: "Mandlebrot Fractal Explorer",
    subtitle: "An app that renders and allows you to explore the Madlebrot (and burning ship) fractal",
    ms_since_epoch: null,
    image: {image: one, alt: "TODO"},
    technologies: [JAVA, GPU],
    links: [
        {url: "https://github.com/Robert-M-Lucas/Mandlebrot-Fractal-GPU", type: GITHUB_LINK}
    ],
    page: FractalEntryPage
};

function FractalEntryPage() {
    return <ProjWrapper>

    <ProjImage image={one} alt={"TODO"} caption={"Image generated by my program. Originally at 10000x10000 but compressed heavily"}/>
    <ProjParagraph>
        This program renders and allows you to explore (pan, zoom in, etc.) the Mandlebrot and burning ship fractal as well as render screenshots at a resolution higher than your monitor.
        In theory you would be able to zoom in infinitely however the double precision limit is hit after around 20 zoom ins.
    </ProjParagraph>
    <ProjParagraph>
        Despite its flaws, this is one of my favourite projects as it was my first project in Java and the fractals look beautiful. It is also a nice combination of maths and computer
        science which I both like.
    </ProjParagraph>
    <ProjParagraph>
        This is one of my older projects, however, and I would like to redo it with some improvements:
        <ul>
            <li>Getting around the double precision limit</li>
            <li>If you zoom in 2x, one pixel should be saved and three new pixels generated instead of a complete regeneration</li>
            <li>The render feature could save to disk as it runs stopping it from being RAM-limited</li>
        </ul>
    </ProjParagraph>
    <ProjImage image={two} alt={"TODO"}/>
    <ProjImage image={three} alt={"TODO"}/>
    <ProjImage image={four} alt={"TODO"}/>
    <ProjImage image={five} alt={"TODO"} caption={"An early test of a more optimised screenshot system"}/>
    </ProjWrapper>;
}