import Pimg from "../../components/project_entry_utils/Pimg.tsx";
import options_code from "./assets/options_code.png";
import code from "./assets/code.png";
import pattern2 from "./assets/pattern2.png";
import pattern from "./assets/pattern.png";
import {GITHUB_LINK} from "../../routes/projects/SingleProjectPage/links.tsx";
import {Project} from "../../routes/projects/SingleProjectPage/project.ts";
import ProjWrapper from "../../components/project_entry_utils/ProjWrapper.tsx";
import Pp from "../../components/project_entry_utils/Pp.tsx";
import {PYTHON} from "../../routes/projects/SingleProjectPage/technology.tsx";
    
export const GeometricPatternProject: Project = {
    currently_working_on: false,
    name: "geometric_pattern",
    title: "Geometric Pattern Generator",
    subtitle: "Generating a geometric pattern for use in future projects",
    ms_since_epoch: null,
    image: {image: pattern, alt: "TODO"},
    technologies: [PYTHON],
    links: [
        {url: "https://github.com/Robert-M-Lucas/TriangleGenerator", type: GITHUB_LINK}
    ],
    page: GeometricPatternEntryPage
};

function GeometricPatternEntryPage() {
    return <ProjWrapper>

    <Pimg image={pattern} alt={"TODO"} caption={"Pattern generated with this project"}/>
    <Pp>
        This is a simple project I've made to generate these geometric patterns which have all sorts of applications such as website backgrounds. 
        It works by generating a grid of squares with lines dividing them into triangles (these lines can generate either way). The points of these squares
        are then translated randomly to create that triangle pattern
    </Pp>
    <Pimg image={pattern2} alt={"TODO"} caption={"Setting the random offsets to 0 demonstrates how it is generated"}/>
    <Pp>
        The colours are generated by finding a point's distance from the four corners and mixing the four corners' colours proportionately. A corner's colour
        can be set to 'None' to make it have no effect. The random color variance is achieved by generating a random shade of grey and adding or subtracting
        it from the triangle's color
    </Pp>
    <Pimg legacyNaturalWidth image={code} alt={"TODO"} caption={"Code for getting the color of a triangle (without random colour variation)"}/>
    <Pimg legacyNaturalWidth image={options_code} alt={"TODO"} caption={"Options available"}/>
    </ProjWrapper>;
}