import {ArrowDownSquare, ArrowUpSquare, EnvelopeFill, Github, GooglePlay} from "react-bootstrap-icons";
import bg from "./bg.png";
import cyberFinalist from "./CyberFinalist.png";
import {Header} from "../../components/Header/Header.tsx";
import "./index.scss";

export function IndexPage() {
    return <>
        <Header/>

        <img alt="background - fractals" className="bg" src={bg} style={{position: 'absolute', zIndex: -1}} width="100%" />
        <div className="d-flex align-items-center justify-content-center text-center" style={{minHeight: '95%'}}>
            <div className="p-2 bd-highlight text-center" style={{maxWidth: '1000px'}}>
                <div className="appear stay-shown" style={{paddingBottom: '120px'}}>
                    <h1 style={{fontFamily: 'Fira Mono,sans-serif', fontSize: '100px', marginBottom: 0, marginTop: 0, fontWeight: 'bolder'}} id="title">&gt; _</h1>
                    <h3 className="text-muted">
                        Student - Software Developer
                    </h3>
                </div>
                <div className="appear stay-shown trans-delay-500" style={{paddingBottom: '30px'}}>
                    <a href="/projects"><button type="button" className="btn btn-primary"><b>See projects</b></button></a>
                    <b><p className="text-muted">Background image generated by <a href="/projects/fractal">this project</a></p></b>
                </div>
                <div className="appear stay-shown trans-delay-1000" style={{paddingBottom: '90px'}}>
                    <a href="#about"><ArrowDownSquare width={40} height={40} /></a>
                </div>
            </div>
        </div>
        <section id="about">
            <div className="container text-center" style={{minHeight: '100%'}}>
                <hr />
                <div className="d-flex align-items-center justify-content-center text-center" style={{minHeight: '100vh'}}>
                    <div className="p-2 bd-highlight text-center" style={{maxWidth: '800px'}}>
                        <div className="appear stay-shown" style={{paddingBottom: '50px'}}>
                            <h1 style={{fontSize: '50px', paddingBottom: '30px'}}>About Me</h1>
                            <h5 style={{fontSize: '1.1rem', paddingBottom: '30px'}}>
                                Currently studying Computer Science at the University of Bath pursuing a degree and career in computer science.
                                I have had experience teaching students STEM at a club I founded at my sixth form as well as having completed work experience at
                                <a href="https://www.vestcom.com/">Vestcom</a>, gaining experience in QA testing and DevOps.
                            </h5>
                            <h5 style={{fontSize: '1.1rem'}}>
                                I'm always working on new projects and expanding my knowledge so check back on the
                                <a href="/projects">projects page</a>
                                every now and again.
                            </h5>
                        </div>
                        <div className="appear stay-shown trans-delay-500">
                            <a className="trans-delay-500" href="https://thenationalcyberawards.org/2022-finalists/" target="_blank"><img src={cyberFinalist} alt="Cyber Finalist" width="300px" /></a>
                        </div>
                        <div style={{paddingTop: '30px'}} className="appear stay-shown trans-delay-1000">
                            <a href="#contact">
                                <ArrowDownSquare width={40} height={40} />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="contact">
            <div className="container text-center" style={{minHeight: '50%'}}>
                <hr />
                <div className="d-flex align-items-center justify-content-center text-center" style={{minHeight: '50vh'}}>
                    <div className="p-2 bd-highlight text-center">
                        <h1 style={{fontSize: '50px', paddingBottom: '25px'}} className="appear stay-shown">Contact &amp; Accounts</h1>
                        <a href="https://github.com/Robert-M-Lucas/" className="appear delayed-appear stay-shown" target="_blank"><button type="button" className="btn btn-warning me-2"><Github width={20} height={20} />&nbsp;Github</button></a>
                        <a href="https://play.google.com/store/apps/developer?id=Robert+App+Dev" className="appear delayed-appear stay-shown" target="_blank"><button type="button" className="btn btn-success me-2"><GooglePlay width={20} height={20} />&nbsp;Google Play</button></a>
                        <a href="mailto:robert01.lucas@outlook.com" className="appear delayed-appear stay-shown" target="_blank"><button type="button" className="btn btn-primary me-2"><EnvelopeFill width={20} height={20} />&nbsp;Email</button></a>
                        <h5 style={{fontSize: '1.1rem', paddingTop: '25px'}} className="appear delayed-appear stay-shown">
                            Telephone: <a href="tel:+44 751251 0075">+44 751251 0075</a>
                        </h5>
                        <div style={{paddingTop: '30px'}} className="appear stay-shown trans-delay-1000">
                            <a href="#top">
                                <ArrowUpSquare width={40} height={40} />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </>;
}